#!/bin/sh

# 커밋 메시지를 초기화하고 기본 템플릿 삽입
cat <<EOF > "$1"

# === Commit Type Reference ===
# Docs: 문서 수정

# === Code Change ===
# Feat: 새로운 기능 추가
# Refactor: 코드 리팩터링
# Chore: 빌드, 설정파일 수정
# Design: UI / CSS 등 스타일 수정
# BREAKING: 대규모 API 변경

# Rename: 파일 또는 폴더명 수정
# Remove: 파일 삭제

# === Code Maintain ===
# Style: 코드 포맷 변경, 세미 콜론 누락, 코드 수정 X
# Comment: 주석 추가 및 변경

# === Bug Fix ===
# Fix: 버그 수정
# HOTFIX: 치명적 버그 긴급 수정
EOF

